In [1]:
import cv2
import numpy as np
import face_recognition

In [2]:
names = ['muthu','thilaga','sundar','nithin','akshay']
folder = '/home/pracas/Machine Vision/Workshop/workshop photos/test'

In [3]:
face_encodings = []

for i in range(0,5):
    file_name = folder +"/"+names[i]+".jpg"
    #print(file_name)
    image = cv2.imread(file_name)
    image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    known_image = cv2.resize(image, (0, 0), fx=0.35, fy=0.35)
    face_locations = face_recognition.face_locations(known_image)
    (t,r,b,l) = face_locations[0]
    face = known_image[t:b,l:r]
    known_encoding = face_recognition.face_encodings(face)[0]
    face_encodings.append(known_encoding)
print(face_encodings)

[array([ -1.22158356e-01,   4.40382101e-02,   2.52580270e-02,
        -6.02066666e-02,  -1.84733272e-02,  -1.09078214e-02,
        -2.51406617e-02,  -1.37352675e-01,   1.87836260e-01,
        -1.90869957e-01,   1.99135065e-01,   7.73906708e-02,
        -1.86528876e-01,  -1.44236863e-01,  -6.73861802e-02,
         1.06702566e-01,  -8.64678323e-02,  -1.75177440e-01,
        -4.35108207e-02,  -8.53168145e-02,  -4.49115895e-02,
        -7.10825995e-03,   1.41873956e-02,  -3.05722803e-02,
        -1.16448455e-01,  -2.61300713e-01,  -1.23777032e-01,
        -9.65825394e-02,   3.29768248e-02,  -5.40718399e-02,
        -6.09276444e-03,  -3.22833657e-04,  -1.62083179e-01,
        -3.83841768e-02,  -1.25500653e-02,   1.28706738e-01,
        -4.51002307e-02,   2.91717052e-03,   2.18804225e-01,
         4.40036058e-02,  -1.03458807e-01,  -6.72926754e-02,
        -4.11198474e-04,   2.83150196e-01,   9.17951614e-02,
         1.72409490e-02,   3.59972566e-02,  -6.75193444e-02,
         6.95379078e-02

In [ ]:
file_name = folder +"/"+"sundaresan_test"+".jpg"
unknown_image = cv2.imread(file_name)
unknown_image = cv2.resize(unknown_image, (0, 0), fx=0.35, fy=0.35)
unknown_image = cv2.cvtColor(unknown_image,cv2.COLOR_BGR2RGB)
face_locations = face_recognition.face_locations(unknown_image)
(t,r,b,l) = face_locations[0]
face = unknown_image[t:b,l:r]
unknown_encoding = face_recognition.face_encodings(face)[0]
#print(unknown_encoding)
face_distances = face_recognition.face_distance(face_encodings,unknown_encoding)
print(face_distances.argmin())

In [7]:
file_name = folder +"/"+"VID_20180729_152440452.mp4"
cap = cv2.VideoCapture(file_name)
cv2.namedWindow("video")
cv2.waitKey()
frame_count = 0
while(cap.isOpened()):
    ret, frame = cap.read()
    frame_count = frame_count + 1
    if ret == True :
        if(frame_count%15 == 0):
            frame = cv2.resize(frame, (0, 0), fx=0.4, fy=0.4)
            frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
            face_locations = face_recognition.face_locations(frame)
            if(len(face_locations)>0):
                for (t, r, b, l) in face_locations:
                    unknown_encoding = face_recognition.face_encodings(frame, [(t, r, b, l)])[0]
                    face_distances = face_recognition.face_distance(face_encodings,unknown_encoding)
                    print(face_distances)
                    text =""
                    if(np.min(face_distances)<0.4):
                        face_index = np.argmin(face_distances)
                        text = text + names[face_index]
                    cv2.rectangle(frame, (l, t), (r, b), (0, 0, 255), 2)
                    font = cv2.FONT_HERSHEY_COMPLEX_SMALL
                    cv2.putText(frame,text,(l,t), font, 1,(255,0,255),1,cv2.LINE_AA)
            cv2.imshow("video",frame)
            cv2.waitKey(1)
    else:
        break
cap.release()
cv2.destroyAllWindows()

[ 0.71624704  0.53874131  0.68785679  0.72539995  0.80009317]
[ 0.65114789  0.48436246  0.64740383  0.67685392  0.74386431]
[ 0.72925772  0.47927277  0.66540246  0.68998546  0.78627236]
[ 0.61865981  0.26992567  0.62678102  0.54474838  0.71718783]
[ 0.65958584  0.53103848  0.59800823  0.66470988  0.77478856]
[ 0.6008857   0.44321403  0.62459296  0.59908633  0.6782705 ]
[ 0.7076727   0.69448974  0.66796403  0.7478695   0.8728916 ]
[ 0.67671199  0.68384025  0.65394091  0.71008989  0.88295236]
[ 0.6774255   0.65801762  0.60165939  0.74496313  0.90082014]
[ 0.7084398   0.60146343  0.62657821  0.63619536  0.70935282]
[ 0.7451558   0.59651995  0.59945659  0.69435355  0.8209897 ]
[ 0.72137458  0.57175543  0.6216926   0.64541189  0.72140644]
[ 0.71665552  0.57458594  0.65213259  0.70521597  0.73609609]
[ 0.79434024  0.57131301  0.72072461  0.65372198  0.77531039]
[ 0.6420721   0.59371723  0.68001125  0.37419002  0.7206915 ]
[ 0.67514937  0.63188929  0.68606933  0.63321527  0.63396772]
[ 0.6446