#####  References

https://stackoverflow.com/questions/10196198/how-to-remove-convexity-defects-in-a-sudoku-square/11366549#11366549
http://opencvpython.blogspot.in/2012/06/sudoku-solver-part-2.html
http://aishack.in/tutorials/sudoku-grabber-opencv-detection/

In [1]:
#### Import all required libraries
import cv2
import numpy as np
np.set_printoptions(threshold=np.nan)

####  We can initially load an image from a file and later use the webcam to scan a sodoku image


In [2]:
#### Load our input image
image = cv2.imread('./image_data/sudoku1.jpg',0) ## Load image in grayscale using the 0 parameter
org_image = image
cv2.imshow('Original', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#### Find the edges of the image
# Find Canny edges
edged = cv2.Canny(image, 50, 200)
cv2.imshow('1 - Canny Edges', edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# Find contours and print how many were found
ret, contours, hierarchy = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print ("Number of contours found = ", len(contours[0]))
print(type(ret))
print(type(contours))
print(type(hierarchy))

Number of contours found =  140
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>


In [6]:
print(ret)
cv2.imshow('Original', ret)
cv2.waitKey()
cv2.destroyAllWindows()

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0 

In [7]:
print(contours)
cv2.imshow('Original', contours)
cv2.waitKey()
cv2.destroyAllWindows()

[array([[[  3,   1]],

       [[  1,   3]],

       [[  2,   4]],

       [[  2,   7]],

       [[  1,   8]],

       [[  0,   8]],

       [[  1,   9]],

       [[  1,  12]],

       [[  2,  13]],

       [[  2,  22]],

       [[  1,  23]],

       [[  2,  24]],

       [[  2,  48]],

       [[  1,  49]],

       [[  1,  55]],

       [[  2,  56]],

       [[  2,  70]],

       [[  1,  71]],

       [[  1,  82]],

       [[  2,  83]],

       [[  2,  87]],

       [[  1,  88]],

       [[  1,  95]],

       [[  2,  96]],

       [[  2, 108]],

       [[  1, 109]],

       [[  1, 119]],

       [[  2, 120]],

       [[  2, 128]],

       [[  1, 129]],

       [[  1, 135]],

       [[  2, 136]],

       [[  2, 152]],

       [[  1, 153]],

       [[  1, 167]],

       [[  2, 168]],

       [[  1, 169]],

       [[  1, 170]],

       [[  2, 171]],

       [[  2, 175]],

       [[  1, 176]],

       [[  2, 177]],

       [[  2, 184]],

       [[267, 184]],

       [[267, 183]],

       [[

TypeError: mat is not a numpy array, neither a scalar

In [8]:
print(hierarchy)

[[[-1 -1 -1 -1]]]


In [9]:
#### Sort Contours by area - Function

def get_contour_areas(contours):
    # returns the areas of all contours as list
    all_areas = []
    for cnt in contours:
        area = cv2.contourArea(cnt)
        all_areas.append(area)
    return all_areas

# Sort contours large to small
sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)
c = sorted_contours[0]
print(c)


[[[  3   1]]

 [[  1   3]]

 [[  2   4]]

 [[  2   7]]

 [[  1   8]]

 [[  0   8]]

 [[  1   9]]

 [[  1  12]]

 [[  2  13]]

 [[  2  22]]

 [[  1  23]]

 [[  2  24]]

 [[  2  48]]

 [[  1  49]]

 [[  1  55]]

 [[  2  56]]

 [[  2  70]]

 [[  1  71]]

 [[  1  82]]

 [[  2  83]]

 [[  2  87]]

 [[  1  88]]

 [[  1  95]]

 [[  2  96]]

 [[  2 108]]

 [[  1 109]]

 [[  1 119]]

 [[  2 120]]

 [[  2 128]]

 [[  1 129]]

 [[  1 135]]

 [[  2 136]]

 [[  2 152]]

 [[  1 153]]

 [[  1 167]]

 [[  2 168]]

 [[  1 169]]

 [[  1 170]]

 [[  2 171]]

 [[  2 175]]

 [[  1 176]]

 [[  2 177]]

 [[  2 184]]

 [[267 184]]

 [[267 183]]

 [[268 182]]

 [[268 180]]

 [[267 179]]

 [[268 178]]

 [[268 151]]

 [[267 150]]

 [[267  80]]

 [[268  79]]

 [[268  32]]

 [[267  31]]

 [[267  29]]

 [[268  28]]

 [[268  24]]

 [[267  23]]

 [[267   6]]

 [[269   4]]

 [[268   5]]

 [[267   4]]

 [[267   2]]

 [[266   1]]

 [[255   1]]

 [[254   2]]

 [[248   2]]

 [[247   1]]

 [[245   1]]

 [[244   2]]

 [[232

In [10]:
#### We assume the Largest contour is the outer border of our sudoku 
cv2.drawContours(image, [c], -1, (255,0,0), 3)
cv2.imshow('Contours by area', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
#### Next lets extract this part of the image alone 
peri = cv2.arcLength(c, True)
approx = cv2.approxPolyDP(c, 0.02 * peri, True)
print(peri)
print(approx)

928.8944424390793
[[[  1   3]]

 [[  2 184]]

 [[267 184]]

 [[266   1]]]


In [13]:
##### Function to order the vertices of the contour as returned by the approx function
##### [ TOP-LEFT, TOP-RIGHT, BOTTOM-RIGHT, BOTTOM-LEFT ]
##### First take the sum of x,y coordinates. TOP-LEFT has least sum, and BOTTOM-RIGHT has maximum sum. 
##### Next find the difference, ie y-x. TOP-RIGHT has minimum and BOTTOM-LEFT has maximum. 
##### Return points as per the new order
def order(h):
        h = h.reshape((4,2))
        hnew = np.zeros((4,2),dtype = np.float32)
        add = h.sum(1)
        hnew[0] = h[np.argmin(add)]
        hnew[2] = h[np.argmax(add)]
        diff = np.diff(h,axis = 1)
        hnew[1] = h[np.argmin(diff)]
        hnew[3] = h[np.argmax(diff)]  
        return hnew

In [14]:
##### Use the function created earlier to get the values in order
new_approx = order(approx)
print(approx)
print(new_approx)

[[[  1   3]]

 [[  2 184]]

 [[267 184]]

 [[266   1]]]
[[  1.   3.]
 [266.   1.]
 [267. 184.]
 [  2. 184.]]


In [15]:
#### Find distance between 2 points and get the maximum length of a side
import math
def distance(point1, point2):
    dist = pow((point2[0] - point1[0]),2) + pow((point2[1] - point1[1]),2)
    dist = math.sqrt(dist)
    return int(dist)
def get_max_length(points):
    length = 0
    for i in range(0,len(points)):
        if(i == (len(points)-1)):
            len1 = distance(points[i], points[0])
        else:
            len1 = distance(points[i], points[i+1])
        print(len1)
        if(len1 > length):
            length = len1
    return length

In [16]:
#### Apllying Warp transform to crop the region of interest
side = get_max_length(new_approx)
new_points = np.float32([[0,0], [side,0], [side,side], [0,side]])
print(new_points)

M = cv2.getPerspectiveTransform(new_approx, new_points)
 
warped = cv2.warpPerspective(org_image, M, (side,side))
 
cv2.imshow('warpPerspective', warped)
cv2.waitKey(0)
cv2.destroyAllWindows()

265
183
265
181
[[  0.   0.]
 [265.   0.]
 [265. 265.]
 [  0. 265.]]


In [17]:
##### Find horizontal lines in the image
kernel = np.ones((5,5), np.uint8)
Erosion = cv2.erode(warped, kernel, iterations = 1)
cv2.imshow('Erosion', Erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
lines = cv2.HoughLinesP(Erosion, 1, np.pi / 45, 200, 5)
print(lines.shape)
print(lines)

for [[x1, y1, x2, y2]] in lines:
    cv2.line(Erosion, (x1, y1), (x2, y2),(0, 255, 0), 3)

cv2.imshow('Probabilistic Hough Lines', Erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

AttributeError: 'NoneType' object has no attribute 'shape'